server:
  port: 8040
spring:
  application:
    name: microservice-getway-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    ueser-route: #该配置方式中，user-route只是给路由一个名称，可以任意起名
      service-id: microservice-provider-user
      path: /user/**
  ## ignored-services: microservice-provider-user, microservice-comsumer-movie
