spring:
  application:
    name: eureka-ha

---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      #将自己注册到peer2这个eureka上面去
      defaultZone: http://peer2:8762/eruka/, http://peer3:8763/eruka/


---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      #将自己注册到peer2这个eureka上面去
      defaultZone: http://peer1:8761/eruka/, http://peer3:8763/eruka/

---
spring:
  profiles: peer3
server:
  port: 8763
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      #将自己注册到peer2这个eureka上面去
      defaultZone: http://peer1:8761/eruka/, http://peer2:8762/eruka/